const TestPudgyPenguins = artifacts.require("TestPudgyPenguins");
const TestInvisibleFriends = artifacts.require("TestInvisibleFriends");
const TestMoonbirds = artifacts.require("TestMoonbirds");
const TestRektGuy = artifacts.require("TestRektGuy");
const TestBoredApes = artifacts.require("TestBoredApes");
const TestERC721 = artifacts.require("TestERC721");
const TestAzuki = artifacts.require("TestAzuki");
const TestCaptainz = artifacts.require("TestCaptainz");
const TestMutantApes = artifacts.require("TestMutantApes");
const TestFriendshipBracelets = artifacts.require("TestFriendshipBracelets");
const TestMutantHoundCollars = artifacts.require("TestMutantHoundCollars");
const TestDoodles = artifacts.require("TestDoodles");
const TestCloneX = artifacts.require("TestCloneX");
const TestMilady = artifacts.require("TestMilady");
const TestSewerPass = artifacts.require("TestSewerPass");
const TestChecks = artifacts.require("TestChecks");
const TestMfers = artifacts.require("TestMfers");

module.exports = function (deployer, _network, accounts) {
  deployer.deploy(TestERC721);
  deployer.deploy(TestAzuki);
  deployer.deploy(TestPudgyPenguins);
  deployer.deploy(TestInvisibleFriends);
  deployer.deploy(TestMoonbirds);
  deployer.deploy(TestRektGuy);
  deployer.deploy(TestBoredApes);
  deployer.deploy(TestMutantApes);
  deployer.deploy(TestMutantHoundCollars);
  deployer.deploy(TestCaptainz);
  deployer.deploy(TestFriendshipBracelets);
  deployer.deploy(TestDoodles);
  deployer.deploy(TestCloneX);
  deployer.deploy(TestMilady);
  deployer.deploy(TestSewerPass);
  deployer.deploy(TestChecks);
  deployer.deploy(TestMfers);
};