name: Unit Tests

on: push

jobs:
  ci:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Setup NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Show NodeJS version    
        run: npm --version
      - name: Install Truffle
        run: npm install truffle -g
      - name: NPM install
        run: npm ci
      - name: Run Truffle Test with CI=true for Codechecks  
        run: CI=true truffle test
      # - name: Run Codechecks
      #   run: npx codechecks
      # - name: Run Test Coverage
      #   run: truffle run coverage