name: Unit Tests

on: push

jobs:
  setupEnvironment:
    name: Set Up Environment
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Show NodeJS version    
        run: npm --version
      - name: NPM install
        run: npm install   
      - name: Run Truffle Test with CI=true for Codechecks  
        run: truffle test
